## Import librearies

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
 # to see better in Jupyter notebook / lab

In [2]:
import numpy as np # for numbers, NaN values etc. 
import pandas as pd # for excel tables etc

In [3]:
from bs4 import BeautifulSoup # import to read HTML file

In [4]:
import os # for reading file names in photo directory

In [5]:
import re # for finding missing photos

## Load excel file

In [6]:
df = pd.read_excel(r'master.xlsx')

In [7]:
df

,id,long,lat,n_bicycle_parking,n_tel_o_fun,Built density (2d built area / void) in 250 meter radius,n_auto_tel,Centrality (gravity) score for each building within 15 min. walk r.,building's street-facing front Distance from parcel limits (0 line) in meters,n_parks,...,Amount of walkalbe Religious buildings (15 min.),Amount of walkable street workout equipment (15 min.),Distance from the Sea in meteres,Distance to nearest bicycle route in meters,Amount of gas stations in 1k radius,Geo point via Flicker,Amount of walkable hospitals and clinics 15. m radius,n_kindergartens,primary,secondary
0,1698,34.763906,32.043899,0,0,0.163702,5,0.284663,1.826463e+00,20,...,1,9,1624.112200,840.408268,1,372,0,1,arab,early
1,1700,34.764112,32.043826,2,99,0.162582,22,0.244624,4.498390e-01,173,...,24,2,1640.330240,831.516629,0,0,4,23,arab,early
2,2110,34.759574,32.056483,7,83,0.123723,9,0.270562,0.000000e+00,236,...,25,5,1005.625262,1660.117843,6,396,7,25,eclectic,arab_neoclassicism
3,2143,34.747829,32.035631,8,68,0.167012,2,0.364729,2.043400e+00,193,...,17,4,349.219875,2108.914354,8,180,6,17,eclectic,arab_neoclassicism
4,2203,34.747280,32.037557,8,88,0.171806,2,0.353015,2.005172e+03,179,...,14,5,350.104553,1949.799785,6,396,5,14,arab,early
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,65652,34.769927,32.041468,5,39,0.279996,10,0.280203,1.977016e+01,131,...,15,10,2127.083640,1183.272165,3,42,2,14,eclectic,arab_neoclassicism
696,65937,34.770170,32.059200,14,249,0.392666,46,0.299048,4.963656e+00,149,...,25,8,510.805234,517.820441,0,306,3,19,eclectic,arab_neoclassicism
697,65938,34.757271,32.054239,8,189,0.405160,44,0.289785,1.200000e-10,139,...,20,6,524.167714,505.240438,6,396,3,17,else,else
698,205265,34.762882,32.056560,9,167,0.466160,44,0.328646,1.783000e-03,179,...,33,7,555.908392,51.569983,5,396,7,12,international,florentin_modernist
699,?,34.758355,32.049357,0,0,0.163702,5,0.284663,1.826463e+00,20,...,1,9,1624.112200,840.408268,1,372,0,1,eclectic,international_neoclassicism

In [8]:
df.dtypes

id                                                                                 object
long                                                                              float64
lat                                                                               float64
n_bicycle_parking                                                                   int64
n_tel_o_fun                                                                         int64
Built density (2d built area / void) in 250 meter radius                          float64
n_auto_tel                                                                          int64
Centrality (gravity) score for each building within 15 min. walk r.               float64
 building's street-facing front Distance from parcel limits (0 line) in meters    float64
n_parks                                                                             int64
Building's height (simple)                                                        float64
Historical buildings within 15 min. walk                                            int64
Parcel size (square meters)                                                         int64
n_playgrounds                                                                       int64
tsunami_flood_line                                                                  int64
Building's volume in cubic meter                                                  float64
Amount of walkalbe Religious buildings (15 min.)                                    int64
Amount of walkable street workout equipment (15 min.)                               int64
Distance from the Sea in meteres                                                  float64
Distance to nearest bicycle route in meters                                       float64
Amount of gas stations in 1k radius                                                 int64
Geo point via Flicker                                                               int64
Amount of walkable hospitals and clinics 15. m radius                               int64
n_kindergartens                                                                     int64
primary                                                                            object
secondary                                                                          object
dtype: object

In [9]:
df.select_dtypes(np.number)

,long,lat,n_bicycle_parking,n_tel_o_fun,Built density (2d built area / void) in 250 meter radius,n_auto_tel,Centrality (gravity) score for each building within 15 min. walk r.,building's street-facing front Distance from parcel limits (0 line) in meters,n_parks,Building's height (simple),...,tsunami_flood_line,Building's volume in cubic meter,Amount of walkalbe Religious buildings (15 min.),Amount of walkable street workout equipment (15 min.),Distance from the Sea in meteres,Distance to nearest bicycle route in meters,Amount of gas stations in 1k radius,Geo point via Flicker,Amount of walkable hospitals and clinics 15. m radius,n_kindergartens
0,34.763906,32.043899,0,0,0.163702,5,0.284663,1.826463e+00,20,7.84,...,0,1845.885637,1,9,1624.112200,840.408268,1,372,0,1
1,34.764112,32.043826,2,99,0.162582,22,0.244624,4.498390e-01,173,10.91,...,0,19620.826018,24,2,1640.330240,831.516629,0,0,4,23
2,34.759574,32.056483,7,83,0.123723,9,0.270562,0.000000e+00,236,9.35,...,0,2701.911262,25,5,1005.625262,1660.117843,6,396,7,25
3,34.747829,32.035631,8,68,0.167012,2,0.364729,2.043400e+00,193,21.42,...,0,4987.195327,17,4,349.219875,2108.914354,8,180,6,17
4,34.747280,32.037557,8,88,0.171806,2,0.353015,2.005172e+03,179,18.18,...,0,4161.727949,14,5,350.104553,1949.799785,6,396,5,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,34.769927,32.041468,5,39,0.279996,10,0.280203,1.977016e+01,131,10.57,...,0,2727.262389,15,10,2127.083640,1183.272165,3,42,2,14
696,34.770170,32.059200,14,249,0.392666,46,0.299048,4.963656e+00,149,22.01,...,0,4685.929198,25,8,510.805234,517.820441,0,306,3,19
697,34.757271,32.054239,8,189,0.405160,44,0.289785,1.200000e-10,139,22.19,...,0,5171.375706,20,6,524.167714,505.240438,6,396,3,17
698,34.762882,32.056560,9,167,0.466160,44,0.328646,1.783000e-03,179,21.01,...,0,16046.427083,33,7,555.908392,51.569983,5,396,7,12
699,34.758355,32.049357,0,0,0.163702,5,0.284663,1.826463e+00,20,7.84,...,0,1845.885637,1,9,1624.112200,840.408268,1,372,0,1

In [10]:
df.select_dtypes('category')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[700 rows x 0 columns]

## Import images

keep building id column from excel

In [11]:
id_lst = df['id']

In [12]:
id_df = pd.DataFrame(id_lst)

Load files from the photo folder

In [13]:
phot_lst = os.listdir('../photos') # returns list

In [14]:
len(phot_lst)

764

In [15]:
id_df['img_src'] = '' # create empty column to add data to

In [16]:
phot_lst

['אאורבך 8-בר-הופמן-14_8840.jpg',
 'אאורבך-4(2)_12146.jpg',
 'אאורבך-4_12146.jpg',
 'אאורבך-5_9412.jpg',
 'אאורבך-6_8596.jpg',
 'אאורבך-7_12928.jpg',
 'אבינרי יצחק 8-(חזית אחורית)_7563.jpg',
 'אבינרי-יצחק-4-4-,א׳חביבי-אמיל-3_12704.jpg',
 'אבינרי-יצחק-6_2598.jpg',
 'אבן-רשד-12-בית-רעים-3-מתוקן_11663.jpg',
 'אבן-רשד-12-בית-רעים-3_11663.jpg',
 'אוז׳שקובה-1-פושקין-9-דנטה-6_7035.jpg',
 'אוז׳שקובה-2-פושקין-11-(חזית)_2538.jpg',
 'אוז׳שקובה-2-פינת-פושקין-11_2538.jpg',
 'אוז׳שקובה-4_2556.jpg',
 'אוריאל-אקוסטה-11_2334.jpg',
 'אוריאל-אקוסטה-14-12_7028.jpg',
 'אוריאל-אקוסטה-15(1)_2518.jpg',
 'אוריאל-אקוסטה-15_2518.jpg',
 'אוריאל-אקוסטה-16_6383.jpg',
 'אוריאל-אקוסטה-17_2407.jpg',
 'אוריאל-אקוסטה-18-פרנקל-ידידיה-31(2)_6399.jpg',
 'אוריאל-אקוסטה-18-פרנקל-ידידיה-31_6399.jpg',
 'אוריאל-אקוסטה-20-פרנקל-ידידיה-33(2)_6403.jpg',
 'אוריאל-אקוסטה-20-פרנקל-ידידיה-33_6403.jpg',
 'אוריאל-אקוסטה-9_12342.jpg',
 'אחילוף-3_8543.jpg',
 'איילת-השחר-10-ראש-פינה-28_2833.jpg',
 'איילת-השחר-7-ראש פינה-26_2983.jpg',
 'אילת-10_2498.jpg',
 'אילת-14-אוארבך-1_12911.jpg',
 'אילת-16_2577.jpg',
 'אילת-32-פברגט-אנריקה-1_8391.jpg',
 'אילת-36_12295.jpg',
 'אילת-38_12297.jpg',
 'אילת-40-קומפורט-2_8761.jpg',
 'אילת-42-קומפורט-1_8610.jpg',
 'אילת-44_40932.jpg',
 'אילת-46_7170.jpg',
 'אילת-50-אברבנאל-2_2954.jpg',
 'אילת-52-54-אברבנאל-1_2369.jpg',
 'אילת-8-ניצנה-7_7542.jpg',
 'אילת-השחר-10-ראש-פינה-28(2)_2833.jpg',
 'אליעזר-בן-הורקונוס-4_6955.jpg',
 'אלעז- בן-יוסי-2-חנניה-בן-דוסא-27_2309.jpg',
 'אסף-הרופא-40-42_2325.jpg',
 'אפק-6-תרצה-8-סגולה-5_12018.jpg',
 'ארליך-16_10771.jpg',
 'ארליך-18_6458.jpg',
 'ארליך-20_21657.jpg',
 'ארליך-21-שבטי-ישראל-49_2599.jpg',
 'ארליך-27_6481.jpg',
 'בגין מנחם 10-הגדוד העברי(2)-1_2241.jpg',
 'בגין מנחם 10-הגדוד העברי-1_2241.jpg',
 'בגין מנחם 12-הגדוד העברי-3_2260.jpg',
 'בגין-מנחם 12-הגדוד-העברי-3(2)_2260.jpg',
 'בית אשל-11-בן-עזריה-אלעזר-6_41512.jpg',
 'בית-אשל 3-בן-יאיר-פנחס-10_8836.jpg',
 'בית-אשל-12_50980.jpg',
 'בית-אשל-14-בן-יאיר-פנחס-12_8834.jpg',
 'בית-אשל-19_41028.jpg',
 'בית-אשל-1_12040.jpg',
 'בית-אשל-21_41026.jpg',
 'בית-אשל-23_2203.jpg',
 'בית-אשל-25-חנניה-בן-דוסא-28_6899.jpg',
 'בית-אשל-26_12890.jpg',
 'בית-אשל-28_8843.jpg',
 'בית-אשל-31_52708.jpg',
 'בית-אשל-38_8838.jpg',
 'בית-אשל-4-10_40942.jpg',
 'בית-אשל-5-שמעון-הצדיק-22-בן-יאיר-פנחס-7_12461.jpg',
 'בית-אשל-7-שמעון-הצדיק-31_8837.jpg',
 'בן-אחיטוב-1-3-שמואל-בן-עדיה-7_10375.jpg',
 'בן-אחיטוב-13-החרוב-6_11663.jpg',
 'בן-אחיטוב-14_2408.jpg',
 'בן-אחיטוב-17_2886.jpg',
 'בן-אחיטוב-22-24_12346.jpg',
 'בן-זומא-שמעון-2-חנניא-בן-דוסא-19_12899.jpg',
 'בן-יאיר-פנחס-3-שמעון-הצדיק-16(2)_7186.jpg',
 'בן-יאיר-פנחס-3-שמעון-הצדיק-16_7186.jpg',
 'בן-יאיר-פנחס-5-שמעון-הצדיק-20-יוהשע-בן-פרחיה-6_2803.jpg',
 'בן-עזריה-13-שמעון-בן-גמליאל-4_9508.jpg',
 'בן-צבי-5_8842.JPG',
 'בן-שטח-4_7194.jpg',
 'בנבנישתי-18-דרך-שלמה-69_8987.jpg',
 'בנטוב מרדכי-14_11825.jpg',
 'בעל-הטורים-5_52732.jpg',
 'בר-הופמו-17_8839.jpg',
 'בר-הופמן-11_8841.jpg',
 'בר-הופמן-13-אוארבך-10(2)_12912.jpg',
 'בר-הופמן-13-אוארבך-10_12912.jpg',
 'בר-הופמן-15_8917.jpg',
 'בר-הופמן-17_8839.jpg',
 'בר-הופמן-17א_41441.jpg',
 'בר-הופמן-9_10401.jpg',
 'ברגר-אליזבת-12_11831.jpg',
 'ברנדט-וילי-3_11814.jpg',
 'גורקי-12_9372.jpg',
 'גורקי-4_8752.jpg',
 'גורקי-6-פושקין-20-(חזית)_51009.jpg',
 'גורקי-6-פושקין-20_51009.jpg',
 'דה-רוטשילד-בת-שבע-2_10615.jpg',
 'דה-רוטשילד-בת-שבע-3_10588.jpg',
 'דונלו-הרופא-24_11843.jpg',
 'דנטה-17_6799.jpg',
 'דני-קיי-2-תג׳ר-ציונה-9_8829.jpg',
 'דני-קיי-8_7330.jpg',
 'דני-קיי-קמינסקי-6-10(2)_2823.jpg',
 'דני-קיי-קמינסקי-6-10_2823.jpg',
 'דרור-9(2)_12910.jpg',
 'דרור-9_12910.jpg',
 'דרך-בן-צבי-68-70_10437.jpg',
 'דרך-בן-צבי-78_9052.jpg',
 'דרך-יפו-24-הקישון-2_12361.jpg',
 'דרך-שלמה-63-בן-עטר-12_10421.jpg',
 'דרך-שלמה-77_10318.jpg',
 'דרך-שלמה-81-הקישון-87_50439.jpg',
 'דרך-שלמה-83_50815.jpg',
 'ד״ר-ולבה-יואל-3_12289.jpg',
 'האגוז-17-שלוחות-1-הצרי-12-החילוף-22_6789.jpg',
 'האתרוג-16_6913.jpg',
 'האתרוג-24-יאנוש-קורצאק-7-בית-פלט-37_2624.jpg',
 'הגמנסיה העברית 8-יועזר איש הבירה 2-4- 3338 1_8826.jpg',
 'הגמנסיה-העברית 4-6-יועזר-איש-הבירה-5_12257.jpg',
 'הגמנסיה-העברית-5-יועזר-איש-הבירה-7-המלך-חירם-4_12861.jpg',
 'הגמנסיה-העברית-7-יועזר-איש-הבירה 6-יהושוע-בן-פרחיה-3-בן-יאיר-פנחס-6(2)_8955.jpg',
 'הגמנסיה-העברית-7-יועזר-איש-הבירה 6-יהושוע-בן-פרחיה-3-בן-יאיר-פנחס-6_8955.jpg',
 'הגר״א-36-ראש-פינ-25_11660.jpg',
 'הדואר 9-שדרות-ירושלים-12-ליענר-שלמה-1-שמי-יחיאל-2_7375.jpg',
 'הדואר-10(2)_8985.jpg',
 'הדואר-10_8985.jpg',
 'הדואר-12-14_6277.jpg',
 'הדואר-2-רזיאל-דוד-13_9269.jpg',
 'הדואר-4_7282.jpg',
 'הדואר-6_40883.jpg',
 'הדואר-8_7128.jpg',
 'הדולפין-11_6748.jpg',
 'הדולפין-19_51096.jpg',
 'הדולפין-20_41401.jpg',
 'החיטה-3_2438.jpg',
 'החלוצים-13-לווינסקי-57_11852.jpg',
 'החלוצים-14-לוינסקי-55_7348.jpg',
 'החלוצים-16-לווינסקי-48_12056.jpg',
 'החלוצים-21-מטלון-45_9829.jpg',
 'החלוצים-22-מטלון-43_2942.jpg',
 'החלוצים-24-מטלון-46_8764.jpg',
 'החלוצים-32_12962.jpg',
 'החלוצים-33-וולפסון-36_8776.jpg',
 'החלוצים-34-וולפסון-34_12971.jpg',
 'החלוצים-35_12923.jpg',
 'החלוצים-36_12924.jpg',
 'החלוצים-37_12129.jpg',
 'החלוצים-39_8593.jpg',
 'החלוצים-42_52695.jpg',
 'החלוצים-44_12469.jpg',
 'החלוצים-47-פרנקל-ידידיה-58_12009.jpg',
 'החלוצים-50-א׳_8823.jpg',
 'החלוצים-52_12259.jpg',
 'החלוצים-5_52703.jpg',
 'החצוצרה-(מגדל-מים)_0.jpg',
 'החצוצרה-7-(מגדל-מים)-1_0.jpg',
 'החרוב-26_2853.jpg',
 'החרוב-2_2858.jpg',
 'החרוב-30_2331.jpg',
 'החרוב-44_2860.jpg',
 'החרש-37-לבנדה-52_2243.jpg',
 'החרש-39-לבנדה-54_12335.jpg',
 'החרש-41-לבנדה-56_8290.jpg',
 'הלוטוס-8_2857.jpg',
 'הלענה-3-הצרי-24_2855.jpg',
 'המגיד-מדובנא-4_2914.jpg',
 'המלך-חירום-10-שמעיה-1-3(2)_11827.jpg',
 'המלך-חירום-10-שמעיה-1-3_11827.jpg',
 'המלך-חירם 2-יועזר-איש-הבירה-1-3-מרזוק-ועזר-2_7284.jpg',
 'המלך-חירם-15_2763.jpg',
 'המלך-חירם-16-שמעון-הצדיק-4(2)_7433.jpg',
 'המלך-חירם-16-שמעון-הצדיק-4_7433.jpg',
 'המשביר-11_8377.jpg',
 'המשביר-12-לוינסקי-26_41208.jpg',
 'המשביר-15-לוינסקי-28_9473.jpg',
 'המשביר-19_8376.jpg',
 'המשביר-23_12438.jpg',
 'המשביר-24-מטלון-25_50569.jpg',
 'המשביר-4_8735.jpg',
 'המשביר-6_8915.jpg',
 'המשביר-8-10-לוינסקי-33_7325.jpg',
 'הספינה-17_3008.jpg',
 'העליה 29-וולפסון-40_19823.jpg',
 'העליה-10_8374.jpg',
 'העליה-12_8373.jpg',
 'העליה-16-לוינסקי-59_11858.jpg',
 'העליה-18-לווינסקי-52_8912.jpg',
 'העליה-2-יפו-62_8372.jpg',
 'העליה-20_8911.jpg',
 'העליה-22_8371.jpg',
 'העליה-24-מטלון-47_6877.jpg',
 'העליה-26-מטלון-50_12260.jpg',
 'העליה-29-וולפסון-40(2)_19823.jpg',
 'העליה-32_8909.jpg',
 'העליה-34-וולפסון-41_2379.jpg',
 'העליה-36-38-וולפסון-38_8908.jpg',
 'העליה-48-פרנקל-ידידיה-59_8763.jpg',
 'העליה-4_11661.jpg',
 'העליה-50-פרנקל-ידידה-62_11903.jpg',
 'העליה-58_12003.jpg',
 'העליה-60-פלורנטין-59_2607.jpg',
 'העליה-64_11972.jpg',
 'העליה-68_7083.jpg',
 'העליה-70-דרך-שלמה-93_41013.jpg',
 'הצרי-7_2495.jpg',
 'הקישון-25-מטלון-15_10433.jpg',
 'הקישון-34_12362.jpg',
 'הקישון-36-וולפסון-7_2514.jpg',
 'הקישון-38-וולפסון-8_2625.jpg',
 'הקישון-3_2610.jpg',
 'הקישון-43_12363.jpg',
 'הקישון-44-אוריאל-אקוסטה-25_12036.jpg',
 'הקישון-45_2618.jpg',
 'הקישון-46-ידידה-פקנקל-35-אוריאל-אקוסטה-22_10617.jpg',
 'הקישון-47-ידידה-פרנקל-37-כפר-גלעדי-48_11508.jpg',
 'הקישון-48-ידידה-פרנקל-32_6476.jpg',
 'הקישון-49_12220.jpg',
 'הקישון-50_6488.jpg',
 'הקישון-52_11988.jpg',
 'הקישון-54_11990.jpg',
 'הקישון-56_11991.jpg',
 'הקישון-58-פלורנטין-33_8757.jpg',
 'הקישון-59_2588.jpg',
 'הקישון-5_2610.jpg',
 'הקישון-60-פלורנטין-32_12993.jpg',
 'הקישון-63-פלורנטין-35_2572.jpg',
 'הקישון-64_12991.jpg',
 'הקישון-65-פלורנטין-34(2)_12004.jpg',
 'הקישון-65-פלורנטין-34_12004.jpg',
 'הקישון-66_8597.jpg',
 'הקישון-68_12441.jpg',
 'הקישון-69_12440.jpg',
 'הקישון-6_8755.jpg',
 'הקישון-70_12434.jpg',
 'הקישון-71_8946.jpg',
 'הקישון-72_6463.jpg',
 'הקישון-74_6464.jpg',
 'הקישון-75_2293.jpg',
 'הקישון-76_2576.jpg',
 'הקישון-77_2604.jpg',
 'הקישון-78_2574.jpg',
 'הקישון-80-שלמה-79_41187.jpg',
 'הקישון-81_8384.jpg',
 'הקישון-83_8611.jpg',
 'הקישון-8_2562.jpg',
 'הקישון-9-לוינסקי-23_6461.jpg',
 'הרבי-מבכרך-32_2975.jpg',
 'הרבי-מבכרך-34-אוארבך-9_7009.jpg',
 'הרבי-מבכרך-42א_2847.jpg',
 'הרצל 61-השוק 38-וולפסון-18-20-22_8719.jpg',
 'הרצל-100_7018.jpg',
 'הרצל-114-דרך-שלמה-85_41179.jpg',
 'הרצל-140(2)_7388.jpg',
 'הרצל-140_7388.jpg',
 'הרצל-27_7019.jpg',
 'הרצל-28-יפו-32_2511.jpg',
 'הרצל-29_2512.jpg',
 'הרצל-30_8772.jpg',
 'הרצל-31_7060.jpg',
 'הרצל-32_6431.jpg',
 'הרצל-33_7027.jpg',
 'הרצל-34_6387.jpg',
 'הרצל-35-לווינסקי-31_50447.jpg',
 'הרצל-37-לווינסקי-22_2535.jpg',
 'הרצל-38-36-לווינסקי-29(2)_41643.jpg',
 'הרצל-38-36-לווינסקי-29_41643.jpg',
 'הרצל-39_8773.jpg',
 'הרצל-40-לווינסקי-20_8775.jpg',
 'הרצל-41_9414.jpg',
 'הרצל-44_12322.jpg',
 'הרצל-46_52697.jpg',
 'הרצל-48_8844.jpg',
 'הרצל-49-מטלון-23_2918.jpg',
 'הרצל-51-מטלון-24_12310.jpg',
 'הרצל-59-וולפסון-17_12982.jpg',
 'הרצל-64_52704.jpg',
 'הרצל-66-וולפסון-15_8715.jpg',
 'הרצל-67-ידידיה-פרנקל-41_10618.jpg',
 'הרצל-68-וולפסון-16_2797.jpg',
 'הרצל-72_10420.jpg',
 'הרצל-79-פלורנטין-38_8983.jpg',
 'הרצל-80-פרנקל-ידידיה-39_10593.jpg',
 'הרצל-82-ידידה פרנקל-40_8984.jpg',
 'הרצל-83_10430.jpg',
 'הרצל-85_9057.jpg',
 'הרצל-89_10428.jpg',
 'הרצל-98-פלורנטין-36_9048.jpg',
 'השוק-10_11847.jpg',
 'השוק-17-מטלון-31-מרחביה-22(2)_50666.jpg',
 'השוק-17-מטלון-31-מרחביה-22_50666.jpg',
 'השוק-21-סמטת-אלוף-בצלות-9_7171.jpg',
 'השוק-28-מטלון-29_41547.jpg',
 'השוק-3-סמטת-השוק-2_8658.jpg',
 'השוק-30-אלוף בצלות 7-מטלון-32_7421.jpg',
 'השוק-36-וולפסון-23_12980.jpg',
 'השוק-42-ידידיה-פרנקל-43_11482.jpg',
 'השוק-7-לוינסקי-32_8718.jpg',
 'התקומה-40_50685.jpg',
 'וולפסון-13-כפר-גלעדי-37_12983.jpg',
 'וולפסון-19_8714.jpg',
 'וולפסון-21_12981.jpg',
 'וולפסון-3-מזרחי-32_64822.jpg',
 'וולפסון-43-העליה-27_19926.jpg',
 'וולפסון-45-צ׳לנוב-23_8849.jpg',
 'וולפסון-5-מזרחי-33_7022.jpg',
 'ויטל-חיים-1-ידידיה-פרנקל-6-8(2)_9842.jpg',
 'ויטל-חיים-1-ידידיה-פרנקל-6-8_9842.jpg',
 'ויטל-חיים-10_50514.jpg',
 'ויטל-חיים-2-ידידיה-פרנקל-4_50943.jpg',
 'ויטל-חיים-3(2)_7195.jpg',
 'ויטל-חיים-3_7195.jpg',
 'ויטל-חיים-4-6-פלורנטין-5(2)_8869.jpg',
 'ויטל-חיים-4-6-פלורנטין-5_8869.jpg',
 'ויטל-חיים-8-פלורנטין-8_2232.jpg',
 'ויקטור-הוגו-10_7405.jpg',
 'ויקטור-הוגו-13-מיכאלאנג׳לו-35_11451.jpg',
 'ויקטור-הוגו-14_7285.jpg',
 'ויקטור-הוגו-16_6412.jpg',
 'ויקטור-הוגו-18_6989.jpg',
 'ויקטור-הוגו-26_7014.jpg',
 'ויקטור-הוגו-29_7013.jpg',
 'ויקטור-הוגו-30_12290.jpg',
 'ויקטור-הוגו-9_2621.jpg',
 'ולנסיה-13-15-מענית-1-האשכוליות-18_41628.jpg',
 'זבולון-11_9086.jpg',
 'זבולון-13-לווינסקי-53_2822.jpg',
 'זבולון-14-לווינסקי-51_7198.jpg',
 'זבולון-15-לווינסקי-46_10777.jpg',
 'זבולון-21_10399.jpg',
 'זבולון-24-מטלון-39_6822.jpg',
 'זבולון-25-מטלון-44_10419.jpg',
 'זבולון-26-מטלון-42_11845.jpg',
 'זבולון-27_8978.jpg',
 'זבולון-33-וולפסון-35_2374.jpg',
 'חייבי-משה-8-התות-12-החרוב-37_2859.jpg',
 'חנניא-בן-דוסא-14_65285.jpg',
 'חנניא-בן-דוסא-16-18-שמעון-בן-עזאי-3_2824.jpg',
 'חנניא-בן-דוסא-21_6852.jpg',
 'חנניא-בן-דוסא-23-בן-עזריה-אלעזר-12_8833.jpg',
 'חנניא-בן-דוסא-26_2866.jpg',
 'חנניא-בן-דוסא-27-אלעזר-בן-יוסי-2_2309.jpg',
 'חנניה-בן-דוסא-29_6938.jpg',
 'חנניה-בן-דוסא-30-בית-אשל-27_12881.jpg',
 'ידידה פרנקל-61-העליה-41_7230.jpg',
 'ידידה-פרנקל-26-שטרן-אברהם-2_2306.jpg',
 'ידידה-פרנקל-28-שטרן-אברהם-1_6419.jpg',
 'ידידה-פרנקל-61-העליה-41_7230.jpg',
 'ידידיה פרנקל-57-החלוצים-45_7304.jpg',
 'ידידיה-פרנקל-16_6467.jpg',
 'ידידיה-פרנקל-18_2628.jpg',
 'ידידיה-פרנקל-2-אברבנאל-31_2366.jpg',
 'ידידיה-פרנקל-20_12167.jpg',
 'ידידיה-פרנקל-22_2566.jpg',
 'ידידיה-פרנקל-23_6439.jpg',
 'ידידיה-פרנקל-24_6438.jpg',
 'ידידיה-פרנקל-27_6410.jpg',
 'ידידיה-פרנקל-29_2354.jpg',
 'ידידיה-פרנקל-30_2355.jpg',
 'ידידיה-פרנקל-38_11507.jpg',
 'ידידיה-פרנקל-53-זבולון-49_10619.jpg',
 'ידידיה-פרנקל-55-החלוצים-46_7087.jpg',
 'יהדוה-מרגוזה-16_9121.jpg',
 'יהודה-הימית-21_2418.jpg',
 'יהודה-הימית-29_6416.jpg',
 'יהודה-הימית-31_2597.jpg',
 'יהודה-הימית-33_12908.jpg',
 'יהודה-הימית-35_52731.jpg',
 'יהודה-הימית-37-לוינסון-אברהם-2_7436.jpg',
 'יהודה-הימית-43-קיוסו-אלברט-14_11485.jpg',
 'יהודה-הימית-45_10612.jpg',
 'יהודה-הימית-51_7036.jpg',
 'יהודה-הימית-55_7085.jpg',
 'יהודה-הימית-57(2)_8494.jpg',
 'יהודה-הימית-57_8494.jpg',
 'יהודה-הימית-59_11659.jpg',
 'יהודה-הימית-5_6800.jpg',
 'יהודה-הימית-73_2312.jpg',
 'יהודה-מרגוזה-1-3_2882.jpg',
 'יהודה-מרגוזה-12(2)_41598.jpg',
 'יהודה-מרגוזה-12_41598.jpg',
 'יהודה-מרגוזה-14(2)_9102.jpg',
 'יהודה-מרגוזה-14_9102.jpg',
 'יהודה-מרגוזה-16(2)_9121.jpg',
 'יהודה-מרגוזה-25_8429.jpg',
 'יהודה-מרגוזה-28_8476.jpg',
 'יהודה-מרגוזה-38_12882.jpg',
 'יהודה-מרגוזה-40_12880.jpg',
 'יהודה-מרגוזה-5-עולי-ציון-11_8553.jpg',
 'יהושוע-בן-פרחיה-1-הגמנסיה-העברית-10_2572.jpg',
 'יהושוע-בן-פרחיה-2-הגמנסיה-העברית-12_9063.jpg',
 'יהושוע-בן-פרחיה-4-בן-יאיר-פנחס 8-הגמנסיה-העברית-9-11(2)_8986.jpg',
 'יהושוע-בן-פרחיה-4-בן-יאיר-פנחס 8-הגמנסיה-העברית-9-11_8986.jpg',
 'יוסי-בן-יוסי-11_12888.jpg',
 'יוסי-בן-יוסי-13_13011.jpg',
 'יוסי-בן-יוסי-17_2510.jpg',
 'יוסי-בן-יוסי-7_7015.jpg',
 'יועזר-איש-הביר- 9-בן-יאיר-פנחס-4(2)_12464.jpg',
 'יועזר-איש-הבירה-7א_12878.jpg',
 'יועזר-איש-הבירה-7א׳(2)_12878.jpg',
 'יועזר-איש-הבירה-9-בן-יאיר-פנחס-4_12464.jpg',
 'ים-סוף-20_6959.jpg',
 'יפו-16-רענן-8_12139.jpg',
 'יפו-18-רענן-7-9_12133.jpg',
 'יפו-20-מזרחי-4_11869.jpg',
 'יפו-22-מזרחי-1_2919.jpg',
 'יפו-34-המשביר-2_7526.jpg',
 'יפו-36-המשביר-1_8370.jpg',
 'יפו-38-השוק-2_12170.jpg',
 'יפו-40-השוק-1_10427.jpg',
 'יפו-42_2962.jpg',
 'יפו-46-מרחביה-2_9077.jpg',
 'יפו-48-מרחביה-1_7333.jpg',
 'יפו-50-נחלת-בנימין-74_12963.jpg',
 'יפו-60-החלוצים-1_8533.jpg',
 'יפת 51-אבינרי-יצחק-1_2867.jpg',
 'יפת-1-בית-אשל-2_10418.jpg',
 'יפת-100-חייבי-משה-9_6960.jpg',
 'יפת-102-חייבי-משה-10_2370.jpg',
 'יפת-103-מאור-עיניים-2_8510.jpg',
 'יפת-106-החרוב-46-48_6958.jpg',
 'יפת-11-עמיעד-5_12437.jpg',
 'יפת-19_7327.jpg',
 'יפת-21(2)_6812.jpg',
 'יפת-21(3)_6812.jpg',
 'יפת-23(2)_6897.jpg',
 'יפת-23_6897.jpg',
 'יפת-27(2)_7462.jpg',
 'יפת-27_7462.jpg',
 'יפת-29_50982.jpg',
 'יפת-33(2)_12889.jpg',
 'יפת-33_12889.jpg',
 'יפת-39_11820.jpg',
 'יפת-3_8977.jpg',
 'יפת-41_11830.jpg',
 'יפת-43_7224.jpg',
 'יפת-47-יהודה-הימית-67_65937.jpg',
 'יפת-48-עבד-אל-ראוף-אלביטאר-1_41079.jpg',
 'יפת-49_65938.jpg',
 'יפת-51-אבינרי-יצחק-1_2867.jpg',
 'יפת-52_9456.jpg',
 'יפת-54-דה-רוטשילד-בת-שבע-1_6401.jpg',
 'יפת-55_1700.jpg',
 'יפת-57_1698.jpg',
 'יפת-5_10319.jpg',
 'יפת-61_11499.jpg',
 'יפת-63_11402.jpg',
 'יפת-72-ויינר-זאב-7_6963.jpg',
 'יפת-74-ויינר-זאב-6_6963.jpg',
 'יפת-76-בן-אחיטוב-22-24_12346.jpg',
 'יפת-7_9062.jpg',
 'יפת-80_12345.jpg',
 'יפת-82_50556.jpg',
 'יפת-89_8491.jpg',
 'יפת-91(2)_12311.jpg',
 'יפת-91_12311.jpg',
 'יפת-92-סלסלה-30_50623.jpg',
 'יפת-94_50594.jpg',
 'ירושלים-2-רזיאל-דוד-1_40966.jpg',
 'ירושלים-44_7169.jpg',
 'ירושלים-4_2110.jpg',
 'ירושלים-6_2809.jpg',
 'ירושלים-8_12128.jpg',
 'ישראל-מסלנט-35_9031.jpg',
 'כפר-גלעד-29-מטלון-20-פלורנטין_2838.jpg',
 'כפר-גלעדי-1-יפו-30_64526.jpg',
 'כפר-גלעדי-11_41624.jpg',
 'כפר-גלעדי-14-לוינסקי-16_7403.jpg',
 'כפר-גלעדי-16_7402.jpg',
 'כפר-גלעדי-17_7111.jpg',
 'כפר-גלעדי-18_2846.jpg',
 'כפר-גלעדי-19_7334.jpg',
 'כפר-גלעדי-2-יפו-28_7204.jpg',
 'כפר-גלעדי-20_12963.jpg',
 'כפר-גלעדי-22-24_7423.jpg',
 'כפר-גלעדי-29-מטלון-20_2838.jpg',
 'כפר-גלעדי-3_7289.jpg',
 'כפר-גלעדי-5_7287.jpg',
 'כפר-גלעדי-7_7305.jpg',
 'כפר-גלעדי-9_7288.jpg',
 'כ״ץ-יעקוב-יוסף-4_11864.jpg',
 'לוינסקי-10-א׳_6900.jpg',
 'לוינסקי-12-הקישון-12_2611.jpg',
 'לוינסקי-14-הקישון-11_8868.jpg',
 'לוינסקי-21-הקישון-10_41403.jpg',
 'לוינסקי-24_2917.jpg',
 'לוינסקי-27-כפר-גלעדי-11_41624_41624.jpg',
 'לוינסקי-34_2927.jpg',
 'לוינסקי-8-מזרחי-10_2995.jpg',
 'למרטין-10-שדרות-ירושלים-79(2)_9000.jpg',
 'למרטין-15-עזה-34_8436.jpg',
 'למרטין-16_2905.jpg',
 'למרטין-17_50589.jpg',
 'למרטין-30-שדרות -ירושלים 101_8465.jpg',
 'למרטין-30-שדרות-ירושלים-101_8465.jpg',
 'למרטין-34-שדרות ירושלים 105-הלה טוני-1_2236.jpg',
 'למרטין-34-שדרות-ירושלים-105-הלה-טוני-1(2)_2236.jpg',
 'למרטין-4-שדרות-ירושלים-75-מיכאלנגלו-38_12130.jpg',
 'למרטין-8-שדרות-ירושלים-77_11943.jpg',
 'מגן-אברהם-10-בעלי-התוספות-15_12909.jpg',
 'מזרחי-3_2805.jpg',
 'מזרחי-5_9034.jpg',
 'מזרחי-6_9032.jpg',
 'מזרחי-8-לוינסקי-17_7377.jpg',
 'מזרחי-9-לוינסקי-19_2799.jpg',
 'מטלון-18-כפר-גלעדי-28_7227.jpg',
 'מטלון-28_50628.jpg',
 'מטלון-3-מרכלת-17_41055.jpg',
 'מטלון-30_50667.jpg',
 'מטלון-34-השוק-19_11868.jpg',
 'מטלון-5-רענן-28_8158.jpg',
 'מטלון-6-רענן-30_2365.jpg',
 'מטלון-7-רענן-25_6826.jpg',
 'מטלון-74_18670.jpg',
 'מטלון-74א׳_7494.jpg',
 'מיכאלאנג׳לו-22(2)_41113.jpg',
 'מיכאלאנג׳לו-22_41113.jpg',
 'מיכאלאנג׳לו-28-פושקין-2_7315.jpg',
 'מיכאלאנג׳לו-30-פושקין-1-ראסין-ז׳אן-2(2)_65329.jpg',
 'מיכאלאנג׳לו-33_3021.jpg',
 'מיכאלנג׳לו-33_3021.jpg',
 'מנדס-פרנס-25-געש-16_50592.jpg',
 'מנדס-פרנס-26_7167.jpg',
 'מנדס-פרנס-28_50952.jpg',
 'מנדס-פרנס-9_50653.jpg',
 'מרזוק-ועזר-3_12127.jpg',
 'מרחביה-11-לוינסקי-45_7499.jpg',
 'מרחביה-12-לוינסקי-43_2944.jpg',
 'מרחביה-13-לוינסקי-38_11848.jpg',
 'מרחביה-14-לוינסקי-36_10317.jpg',
 'מרחביה-21-מטלון-33_40957.jpg',
 'מרחביה-3_9075.jpg',
 'מרחביה-4-סמטת-השוק-6_10324.jpg',
 'מרחביה-5_10438.jpg',
 'מרכלת-1-יפו-14_10429.jpg',
 'מרכלת-16_9043.jpg',
 'מרכלת-5-לוינסקי-11_7387.jpg',
 'מרכלת-7-לוינסקי-4א׳_12246.jpg',
 'נועם-7(2)_2813.jpg',
 'נועם-7_2813.jpg',
 'נועם-9(2)_2225.jpg',
 'נועם-9_2225.jpg',
 'נחלת-בניימין-103-לוינסקי-49_41241.jpg',
 'נחלת-בניימין-105-לוינסקי-42(2)_7527.jpg',
 'נחלת-בניימין-105-לוינסקי-42_7527.jpg',
 'נחלת-בניימין-113-מטלון-37_12522.jpg',
 'נחלת-בניימין-115-מטלון-40_8692.jpg',
 'נחלת-בניימין-117_12221.jpg',
 'נחלת-בניימין-123-וולפסון-31_6393.jpg',
 'נחלת-בניימין-129_12222.jpg',
 'נחלת-בניימין-76_8682.jpg',
 'נחלת-בניימין-82-80_8618.jpg',
 'נחלת-בניימין-84-לוינסקי-47_2920.jpg',
 'נחלת-בניימין-86-לוינסקי-40_8614.jpg',
 'נחלת-בניימין-92_8390.jpg',
 'נחלת-בניימין-94-מטלון-35_11378.jpg',
 'נחלת-בנימין-128-פלורנטין-44_8788.jpg',
 'נחלת-בנימין-130_8787.jpg',
 'נחלת-בנימין-140_8686.jpg',
 'נחמה-11-רוחמה-9-11-ניצנה-14-16-סגולה-8(2)_8600.jpg',
 'נחמה-2-תרצה 14-בת-עמי-1_10344.jpg',
 'נחמה-6-רוחמה-16_50638.jpg',
 'נחמה11-רוחמה-9-11-ניצנה-14-16-סגולה-8(2)_8600.jpg',
 'ניצנה-11-ניצנה-11א-ניצנה-11ב-נחמה-13(2)_12314.jpg',
 'ניצנה-9א׳-ניצנה 9ב׳_12196.jpg',
 'ניצנה11-ניצנה-11א-ניצנה-11ב-נחמה-13(3)_12314.jpg',
 'נס-לגויים-49(2)_65652.jpg',
 'נס-לגויים-49_65652.jpg',
 'נס-לגויים-5-למרטין-44_11906.jpg',
 'נס-לגויים-51_41616.jpg',
 'נס-לגויים-7-למרטין-47_11666.jpg',
 'נס-לגויים-9-עזה-66_8422.jpg',
 'סגולה 4-תרצה-10_11636.jpg',
 'סגולה-4-תרצה-10(2)_11636.jpg',
 'סגל-צבי-הרמן-2_50559.jpg',
 'סייפן-2-4-שדרות-יפת-110_2326.jpg',
 'סלסלה-11_12720.jpg',
 'סלסלה-16-הערמון-2_3010.jpg',
 'סלסלה-24-החרוב-1_2825.jpg',
 'סלסלה-26-החרוב-19_50590.jpg',
 'סמטת-3350-3_9411.jpg',
 'ספיר-ברוך-4_7213.jpg',
 'ספיר-ברוך-6_12910.jpg',
 'עאזר-אדיל-3_11374.jpg',
 'עבודת-ישראל-3_7319.jpg',
 'עדולם-10-בכור-ציון-10_11665.jpg',
 'עולי-ציו- 36(2)_3019.jpg',
 'עולי-ציון-1-יפת-9_12330.jpg',
 'עולי-ציון-13_8369.jpg',
 'עולי-ציון-24(2)_7216.jpg',
 'עולי-ציון-24_7216.jpg',
 'עולי-ציון-26_7149.jpg',
 'עולי-ציון-2_12002.jpg',
 'עולי-ציון-30_13011.jpg',
 'עולי-ציון-32_6889.jpg',
 'עולי-ציון-34(2)_8436.jpg',
 'עולי-ציון-34_8436.jpg',
 'עולי-ציון-36_3019.jpg',
 'עולי-ציון-4-רבי-אחא-2_8379.jpg',
 'עולי-ציון-8-עמיעד-13-15-רבי-חנניה-1_7461.jpg',
 'עזה-13-15_11942.jpg',
 'עזה-14_205265.jpg',
 'עזה-24-מיכאלנגלו-42_8972.jpg',
 'עזה-30-דנטא-18-למרטין-13(2)_11860.jpg',
 'פושקין-7-דנטה-5_12246.jpg',
 'פחד-יצחק-13_51009.jpg',
 'פלורנטין-11_8865.jpg',
 'פלורנטין-13_8866.jpg',
 'פלורנטין-14-בן-עטר-1_41618.jpg',
 'פלורנטין-15_8942.jpg',
 'פלורנטין-16_8535.jpg',
 'פלורנטין-17_8589.jpg',
 'פלורנטין-20-בנבנישתי-2_50587.jpg',
 'פלורנטין-24_12907.jpg',
 'פלורנטין-25-שטרן-אברהם-12(2)_8615.jpg',
 'פלורנטין-25-שטרן-אברהם-12_8615.jpg',
 'פלורנטין-26-שדרות-וושינגטון-14_2231.jpg',
 'פלורנטין-28-שדרות-וושינגטון-15_2230.jpg',
 'פלורנטין-30_12142.jpg',
 'פלורנטין-37_2573.jpg',
 'פלורנטין-39_8867.jpg',
 'צנובר-3-דודאים-6_50438.jpg',
 'צנובר-4-דודאים-4_2952.jpg',
 'קדם-35-רב-חובל-11_2616.jpg',
 'קדם-57_8544.jpg',
 'קדם-59_50462.jpg',
 'קדרון-21-23_2575.jpg',
 'קורדיברו-1-ויטל-חיים-5_12879.jpg',
 'קורדיברו-10_8762.jpg',
 'קורדיברו-11_13118.jpg',
 'קורדיברו-12_8604.jpg',
 'קורדיברו-13_2617.jpg',
 'קורדיברו-14_6473.jpg',
 'קורדיברו-15_2590.jpg',
 'קורדיברו-17_7008.jpg',
 'קורדיברו-18_12247.jpg',
 'קורדיברו-19_2509.jpg',
 'קורדיברו-2-ויטל-חיים-7_7196.jpg',
 'קורדיברו-20_2536.jpg',
 'קורדיברו-3_7032.jpg',

In [17]:
for index, row in id_df.iterrows(): # go over everyrow (every building id)
    for i in phot_lst: # compare one building id against all photos
        if i.find(str(row[0])) != -1: # if the photo name is containing the building id
            id_df.iloc[index, 1] = f'./photos/{i}'

In [18]:
img_src_lst = id_df['img_src'].values.tolist()

In [19]:
#img_src_lst

In [20]:
for x,i in enumerate(img_src_lst):
    if i == '':
        print(f'Indx: {x}, id: {id_df["id"][x]}, file name: {i}')

Indx: 34, id: 2373, file name:
Indx: 48, id: 2517, file name:
Indx: 133, id: 2999, file name:
Indx: 137, id: 3020, file name:
Indx: 139, id: 5714, file name:
Indx: 146, id: 6394, file name:
Indx: 155, id: 6418, file name:
Indx: 179, id: 6825, file name:
Indx: 181, id: 6829, file name:
Indx: 186, id: 6888, file name:
Indx: 217, id: 7080, file name:
Indx: 240, id: 7208, file name:
Indx: 246, id: 7226, file name:
Indx: 258, id: 7307, file name:
Indx: 293, id: 8154, file name:
Indx: 302, id: 8375, file name:
Indx: 320, id: 8542, file name:
Indx: 337, id: 8657, file name:
Indx: 365, id: 8828, file name:
Indx: 411, id: 9051, file name:
Indx: 427, id: 9122, file name:
Indx: 442, id: 10363, file name:
Indx: 458, id: 10587, file name:
Indx: 472, id: 11444, file name:
Indx: 509, id: 11920, file name:
Indx: 579, id: 12721, file name:
Indx: 681, id: 51041, file name:
Indx: 699, id: ?, file name:

In [21]:
search_word = "דוד"
for i in phot_lst:
    if i.find(f'{search_word}') > -1:
    #if i.find(f'{search_word}') =! -1:
        print(i)

בגין מנחם 10-הגדוד העברי(2)-1_2241.jpg
בגין מנחם 10-הגדוד העברי-1_2241.jpg
בגין מנחם 12-הגדוד העברי-3_2260.jpg
בגין-מנחם 12-הגדוד-העברי-3(2)_2260.jpg
הדואר-2-רזיאל-דוד-13_9269.jpg
ירושלים-2-רזיאל-דוד-1_40966.jpg
צנובר-3-דודאים-6_50438.jpg
צנובר-4-דודאים-4_2952.jpg
רזיאל-דוד-14-16-רטוש-יונתן-4_2261.jpg
רזיאל-דוד-15_40910.jpg
רזיאל-דוד-17_7193.jpg
רזיאל-דוד-21-23_6801.jpg
רזיאל-דוד-25_2222.jpg
רזיאל-דוד-27-29(2)_2861.jpg
רזיאל-דוד-27-29_2861.jpg
רזיאל-דוד-4_2871.jpg

In [22]:
phot_lst[0].find("c;")

-1

In [23]:
col_list = df.columns.values.tolist()

In [24]:
col_list

['id',
 'long',
 'lat',
 'n_bicycle_parking',
 'n_tel_o_fun',
 'Built density (2d built area / void) in 250 meter radius',
 'n_auto_tel',
 'Centrality (gravity) score for each building within 15 min. walk r.',
 " building's street-facing front Distance from parcel limits (0 line) in meters",
 'n_parks',
 "Building's height (simple)",
 'Historical buildings within 15 min. walk',
 'Parcel size (square meters)',
 'n_playgrounds',
 'tsunami_flood_line',
 "Building's volume in cubic meter",
 'Amount of walkalbe Religious buildings (15 min.)',
 'Amount of walkable street workout equipment (15 min.)',
 'Distance from the Sea in meteres',
 'Distance to nearest bicycle route in meters',
 'Amount of gas stations in 1k radius',
 'Geo point via Flicker ',
 'Amount of walkable hospitals and clinics 15. m radius',
 'n_kindergartens',
 'primary',
 'secondary']

In [59]:
grid_items = '' # create an empty string to append to 
#iterate through each row of dataframe
for index, row in df.iterrows():
    #print(index, ': ', row)
    inside_div_combined = '' # create empty string to append to 
    tmp_div_open = '<div class="building_square" col_header="b">' #  NOTICE: col_header="b"
    #print("STARTING COLUMN PRINT")
    for col_index, col_name in enumerate(col_list):
        tmp_div_inside = f'<p class="{col_name}" style="display:none;">{df.iloc[index, col_index]}</p>' # -----> NOTICE using a 'p'?
        inside_div_combined += tmp_div_inside
    building_card_link = 'http://www.yahoo.com'
    link_open_option = '_blank'
    tmp_div_img = f"""<a href="#" onClick="window.open('{building_card_link}', '_blank') "><img src="{img_src_lst[index]}"></a>""" # change image each row - NOTICE <a> tag    
    inside_div_combined += tmp_div_img # tmp_div_inside + tmp_div_img - BEFORE // CREATED DOUBLE LAST LINE
    tmp_div_close = f'</div>'
    tmp_str = tmp_div_open + inside_div_combined + tmp_div_close
    grid_items += tmp_str

In [60]:
#grid_items

In [61]:
tmp_div_inside

'<p class="secondary" style="display:none;">international_neoclassicism</p>'

Load html > parse to string > insert after '<div class="grid">' > export as html

In [62]:
#test_phrase = '<p> hello, this was inserted into the website html </p>'

In [63]:
html_insert = grid_items

In [64]:
file = open('../index.html', "r") # open local html file (as opposoed to reading from URL)

In [65]:
# Parse the html file
soup = BeautifulSoup(file, 'html.parser')

# Format the parsed html file
strhtm = soup.prettify()

In [66]:
#soup
soup_string = str(soup)

In [67]:
type(strhtm)

str

In [68]:
html_start = strhtm.split('<!-- THIS WILL BE REPLACED WITH INSERTED-->')[0]
html_end = strhtm.split('<!-- THIS WILL BE REPLACED WITH INSERTED-->')[1]

In [69]:
#strhtm

In [70]:
html_combined = [html_start, html_insert, html_end]

In [71]:
joint_str = ''.join(html_combined)

In [72]:
#strhtm

push only mid

In [73]:
# open the file in w mode
# set encoding to UTF-8
with open("../bld_img_atr.html", "w", encoding = 'utf-8') as file:
    
    # prettify the soup object and convert it into a string  
    file.write(grid_items)

1415566

push everything

In [74]:
# open the file in w mode
# set encoding to UTF-8
with open("../output.html", "w", encoding = 'utf-8') as file:
    
    # prettify the soup object and convert it into a string  
    file.write(joint_str)

1428365

In [58]:
#joint_str.encode()

## Create a building card for each image

## Generate an executable (.exe) file from the jupyter-notebook

In [204]:
pip install nbconvert

Note: you may need to restart the kernel to use updated packages.

& was unexpected at this time.

In [186]:
jupyter nbconvert --to script my_notebook.ipynb

SyntaxError: invalid syntax (<ipython-input-186-180559d49540>, line 1)

In [ ]:
pip install pyinstaller
pyinstaller my_notebook.py

In [ ]:
x = txt.encode()